library(dplyr)
library(tidyr)
library(readxl)
source("utils/summary_functions.R")
df = read.csv("data/silver/log.csv")
df_buys = buys_data_treatment(df)
df_pivot = compute_position(df)
df_final = data_join(df_buys, df_pivot)
write.csv(df_final, "data/gold/summary.csv", row.names=FALSE)
